### ISSUE TITLE
Get some feedback

### ISSUE THREAD

**Issue by bashtage** [bashtage/randomgen#1]
@rkern - not really sure how to try and get feedback on this.  It is far from being ready for a PR, but it would be very helpful to get some feedback if this looks like a reasonable approach.  

I've basically gone with the full void-pointer method and exposed 3 functions the return 64 bits, 32 bits and a double.

**Comment by rkern** [comment]
In the interest of boilerplate reduction, I think the `next_` function pointers can be typed rather than `void*`. Similarly, the distribution functions can take `prng_t *` instead of `void *`.

Instead of

```
double random_standard_exponential(void *void_state) {
  prng_t *prng_state = (prng_t *)void_state;
  prng_double next_double = (prng_double)prng_state->next_double;
  return -log(1.0 - next_double(prng_state->state));
}
```

We could have

```
double random_standard_exponential(prng_t *prng_state) {
  return -log(1.0 - prng_state->next_double(prng_state->state));
}
```

**Comment by bashtage** [comment]
@rkern It is mostly done up to a final porting of the def's from RandomState and some fo the distributions.

I implemented an experiment on the core PRNGs (just Xoroshiro128) which presents both CFFI and Ctypes interfaces.  This allows these to be used by Numba and possibly other places where low-level access is possible.   I wrote up some simple examples showing how it is done to prove it works.

https://github.com/bashtage/core-prng/tree/master/examples/numba

I also have lightly wrapped distributions.h with some optional DLL exports so that it could easily be built into a DLL on Windows (it is trivial to build a .so on Linux).  This allows these functions to also be called by Numba.

It is also easy for the distributions to be used in user-land Cython and there are some examples

https://github.com/bashtage/core-prng/tree/master/examples/numba

Do you think this is this a worthwhile effort?  (in the sense that these features would be allowed into NumPy?)

I'll cc @charris since he also seems to be interested in this area of NumPy.

**Comment by rkern** [comment]
I think it would be a good time to take the opportunity move the statefulness of the distributions out of the core PRNGs (i.e. Box-Muller's `has_gauss` crud and the `binomial_t` parameter cache). Unless if we really want to make bit-for-bit comparisons to the current code, I think I'd rather we just drop Box-Muller.

The `binomial_t` structure is just a performance cache so that the intermediate calculated parameters don't have to be recomputed from `n` and `p` for each variate drawn in a large array. Ideally, this would just be done at the start of the method and then discarded once the array returned. The state would never have to have a lifetime outside of the method. I realize this would mean that the array-filling code `disc()` would have to be repeated. I think that for this one method that would be preferable to carrying around that state across all core generators.

**Comment by bashtage** [comment]
I think these are both reasonable to drop.  I suppose most users don't really care where their normals come from and as long as RandomState is kept around for a good while then there will be a BM for anyone interested.

**Comment by rkern** [comment]
I think these should be dropped from the module-level interface: https://github.com/bashtage/randomgen/blob/master/randomgen/generator.pyx#L4318-L4320

If people want to mess around with the internal state of an implicit global, they should have to jump through some hoops.

**Comment by bashtage** [comment]
Thanks - I've removed these.

**Comment by pdebuyl** [comment]
Hi @bashtage 

Thank you for putting randomgen together! It is a nice collection of all RNGs algorithms that I would currently consider for research :-)

I would like to check the status of Cython support. After a short look at the code, what I understand is:

1. Cython is used as the basic glue for the generators
2. The state of the RNGs is stored as a void pointer in a PyCapsule
3. One may use the capsule, but is it not part of the official API

My comment on the API arises from the fact that to have "cimportable" cython code one needs to distribute all the `.pxd` files that would make the generators easy to use from the user's perspective. I must say that I don't know whether it is reasonably feasible to wrap automatically what you provide from Cython.

**Comment by pdebuyl** [comment]
I often prototype in Python, so going from

    import randomgen
    rg = randomgen.MT19937(12345).generator
    x = rg.random_sample()

to

    cimport randomgen
    cdef double x
    cdef randomgen.brng rg = randomgen.MT19937(12345).generator
    x = rg.random_sample()

is kind of ideal for me :-)

I am not sure of how frequent this use case is, though, and I wouldn't want you to spend time on this for my convenience. I have not much development time for the coming weeks, but teach next week a Python / stochastic simulation (maybe with Cython) class, hence my sudden interest :-)

I already pointed you to my blog I believe http://pdebuyl.be/blog/2017/cython-module.html but this was only for a single rng algorithm. The current version is much too slow, as you noticed, and I currently need something faster.

**Comment by pdebuyl** [comment]
For illustration, I have done the following:

1. Move the "cdef" parts of threefry.pyx to a pxd file. See the branch https://github.com/pdebuyl/randomgen/tree/test_cy
2. Attempt to call it from a separate python program:

I copy-paste the result here:

```.py
import get_tf
import randomgen

r = randomgen.threefry.ThreeFry()

print(get_tf.myf(r))

print(get_tf.myf(r))
```

```.pyx
cimport randomgen.threefry
import randomgen.threefry
from randomgen.distributions cimport brng_t

from libc.stdint cimport uint64_t

from cpython.pycapsule cimport PyCapsule_GetPointer

def myf(r):
    cdef brng_t *rng
    cdef uint64_t i
    cdef const char *name = 'BasicRNG'
    rng = <brng_t *> PyCapsule_GetPointer(r.capsule, name)
    i = randomgen.threefry.threefry_next64(<randomgen.threefry.threefry_state *>rng.state)

    return i
```

So it is definitively possible. The PyCapsule thing is nice (I had never used it) and probably more generic but much more cumbersome than "plain Cython".

**Comment by bashtage** [comment]
You don't actually need to understand threefry to use threefry. This is for all of the basicRNGs since they are all forced to expose the same interface via the brng type. This type contains next_uint64, next_uint32 and next_double functions as well as the opaque basicRNG-dependent state.

```
cimport cython
from cpython.pycapsule cimport PyCapsule_GetPointer
from randomgen.common cimport brng_t

def myf(r):
    cdef brng_t *rng
    cdef uint64_t i
    cdef const char *name = 'BasicRNG'
    rng = <brng_t *> PyCapsule_GetPointer(r.capsule, name)
    i = rng.next_uint64(rng.state)

    return i
```

**Comment by pdebuyl** [comment]
This is cool :-)

Currently, one can only access int32, int64 and double values but that means that one should be able to use also the distributions. But they don't preserve state, for instance keeping an already generated normal variable?

**Comment by bashtage** [comment]
Anytime you generate a random value you are going to modify the state in one way or another. 

Under the hoot when you call

```
rng.next_uint64(rng.state)
```

the random number generator is called (in C) taking the state as an argument.  The C code modifies the state so that rng.state is changed in place. 


In terms of using the distributions, a minimal example is something like 

```
cimport cython
from cpython.pycapsule cimport PyCapsule_GetPointer
from randomgen.common cimport brng_t
from randomgen.distributions cimport random_gauss_zig

def myf(r):
    cdef brng_t *rng
    cdef double i
    cdef const char *name = 'BasicRNG'
    rng = <brng_t *> PyCapsule_GetPointer(r.capsule, name)
    i = random_gauss_zig(rng)

    return i
```

Which will return a random double generated using the ZIggurat method. All of the function in randomgen.distributions.pxd just take a `brng*` as their only argument (except one, which takes a complex struct that is used internally to the function).
