### ISSUE TITLE
clarify relation between different parallel operations

### ISSUE THREAD

**Issue by RossBoylan** [bashtage/randomgen#194]
https://bashtage.github.io/randomgen/parallel.html discusses three strategies for getting parallel random numbers, but it doesn't explicitly say what happens if they are combined.  Or whether they should be combined.  I've been adapting some old code, and it has led me to contemplating such mixing.  Though I'm pretty sure I shouldn't :smiley:.  It would be nice if the docs were clearer.

For example, what if one creates `bg = PCG64(888888, 2)` and then does `bg.jumped()`?  If mixing `jumped` and `advance`, is
```python
bg.advance(100)
bg.jumped()
```
equivalent to either `bg.advance(100+JUMP_SIZE)` or `bg.jumped()` alone (`JUMP_SIZE` is the number of steps `jumped` moves according to documents for the bit generator)?

In the following code, do the 2 bit generators end up in the same state, i.e., is using the stream index equivalent to jumping?
```python
bg1 = PCG64(88, 2)
bg1.jumped()
bg2 = PCG64(88, 3)
```

**Comment by bashtage** [comment]
@RossBoylan I have added some notes to the documentation that explain the different methods available:

https://bashtage.github.io/randomgen/parallel.html

Thanks for the feedback.
