### ISSUE TITLE
Document dependency between streams in PCG

### ISSUE THREAD

**Issue by vigna** [bashtage/randomgen#195]
PCG streams obtained by modifying the increment constant are not independent. The topic has been discussed at length for the Rust implementation:

https://github.com/rust-random/rand/issues/907

This should be something the user is made aware of, as having a parameter and talking about "streams" in the documentation gives the idea that the streams are somehow independent.

**Comment by bashtage** [comment]
@vigna I have substantially weakened the language and removed references to "independent" pretty much everywhere, using distinct in place.  Thanks for the feedback.
