### ISSUE TITLE
Future Warning 

### ISSUE THREAD

**Issue by KieranCollins** [bashtage/randomgen#196]
How do I turn off this warning? How do I set the mode to legacy?

'FutureWarning: mode is None which currently defaults to "legacy". After 1.19 this will change to "sequence". To silence this warning, set mode to "legacy" to use legacy seeding or "sequence" to defer seeding to NumPy's SeedSequence.'

**Comment by bashtage** [comment]
Looks like you solved it.  It has to be set when creating a bit generator.
