### ISSUE TITLE
Trouble with examples and `distributions.pxd`

### ISSUE THREAD

**Issue by sseyler** [bashtage/randomgen#20]
Hi there,

Just wanted to start off by saying that I'm really excited about this package and I hope to become engaged with the project eventually. I do a lot of physics simulations that involve stochastic equations and I've been dying to have more straightforward access to fast, robust, thread-safe RNGs via python/cython that can be swapped in/out (without so much recompiling or relying on Intel MKL).

Anyway, I'm currently interested in accessing the distribution generators using a cython `cimport`—e.g. `from randomgen.distributions cimport random_gauss_zig`. Ideally, I would like to generate single Gaussian RVs within a `nogil` block, so I need to avoid Python objects. However, I seem to get stuck with compilation unable proceed past this error from attempting to use the `extending_distributions.pyx` example:

```shell
fatal error: src/distributions/distributions.h: No such file or directory
 #include "src/distributions/distributions.h"
```

I've encountered this problem through the following approaches:
1. `cd` to the `examples/cython` directory and run `python setup.py install` to directly compile the examples.
2. Import `random_gauss_zig` in my own module using `from randomgen.distributions cimport random_gauss_zig`, then compile my extension module from my own `setup.py`. (**Note**: that in the [Docs under Extending > Cython](https://bashtage.github.io/randomgen/extending.html#cython), `import` instead of `cimport` is written; I'm guessing this is a small typo given that the code in `extending_distributions.pyx` has the latter.)
3. Do step 2, but explicitly add the `randomgen/src/distributions` directory to the list of included dirs
4. Do step 3, and also explicitly add `randomgen/src/distributions/distributions.c` to the list of source files when compiling my extension module.

In particular, when I include the `distributions` directory during extension module compilation, I get the set of nasty errors below (so I suspect this isn't a kosher approach):

```shell
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/sstream:38,
                 from /usr/include/c++/7/complex:45,
                 from glrandom.c:869:
/usr/include/c++/7/bits/stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
/usr/include/c++/7/bits/stl_algobase.h:265:56: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
In file included from glrandom.c:653:0:
/usr/include/c++/7/bits/stl_algobase.h:195:5: error: expected unqualified-id before ‘const’
     min(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/7/bits/stl_algobase.h:195:5: error: expected ‘)’ before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:195:5: error: expected ‘)’ before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:195:5: error: expected initializer before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected unqualified-id before ‘const’
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected ‘)’ before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected ‘)’ before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected initializer before ‘const’
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/sstream:38,
                 from /usr/include/c++/7/complex:45,
                 from glrandom.c:869:
/usr/include/c++/7/bits/stl_algobase.h:246:7: error: expected primary-expression before ‘if’
       if (__comp(__b, __a))
       ^~
/usr/include/c++/7/bits/stl_algobase.h:246:7: error: expected ‘}’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:246:7: error: expected ‘;’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:248:7: error: expected unqualified-id before ‘return’
       return __a;
       ^~~~~~
/usr/include/c++/7/bits/stl_algobase.h:268:7: error: expected primary-expression before ‘if’
       if (__comp(__a, __b))
       ^~
/usr/include/c++/7/bits/stl_algobase.h:268:7: error: expected ‘}’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:268:7: error: expected ‘;’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:270:7: error: expected unqualified-id before ‘return’
       return __a;
       ^~~~~~
/usr/include/c++/7/bits/stl_algobase.h:271:5: error: expected declaration before ‘}’ token
     }
     ^
```

I'm using GCC 7.3.0 on Ubuntu 18.04 LTS, Python 2.7.15, Cython 0.28.3, Numpy 1.14.4, etc. I originally installed `randomgen` using `python setup.py install` in the toplevel directory, but I also re-attempted everything with a developer installation via `pip` as well as installing directly from your conda channel (`conda install -c bashtage randomgen`). There's a good chance I'm doing something stupid, so I do apologize in advance if I'm making a facile mistake. Any help would be very much appreciated and I'm happy to provide any useful information I might have left out.

**Comment by bashtage** [comment]
Are you using C++ in your extension?  I'm trying to understand why includes like STL are present?  Can you share a minimal, (not) compilable example?

**Comment by bashtage** [comment]
I just pushed a fix for the examples.

You should be able to do the following:

```
git clone https://github.com/bashtage/randomgen
cd randomgen/randomgen/examples/cython
python setup.py build_ext --inplace
```

and it should work.  I had one level too few in the '..'.

**Comment by sseyler** [comment]
> Are you using C++ in your extension? I'm trying to understand why includes like STL are present?

Ah, yes, sorry for the confusion. I do compile g++ there, but I also tried just compiling with C and gcc (see below). 

> Can you share a minimal, (not) compilable example?

The output below is from running your commands verbatim:

```shell
$ git clone https://github.com/bashtage/randomgen
$ cd randomgen/randomgen/examples/cython
$ python setup.py build_ext --inplace
Compiling extending.pyx because it changed.
Compiling extending_distributions.pyx because it changed.
[1/2] Cythonizing extending.pyx
[2/2] Cythonizing extending_distributions.pyx
running build_ext
building 'extending' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sseyler/Library/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/home/sseyler/Library/miniconda2/include/python2.7 -c extending.c -o build/temp.linux-x86_64-2.7/extending.o
In file included from /home/sseyler/Library/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/sseyler/Library/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/sseyler/Library/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from extending.c:586:
/home/sseyler/Library/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
extending.c:590:10: fatal error: src/distributions/distributions.h: No such file or directory
 #include "src/distributions/distributions.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
```

>  I had one level too few in the '..'

I do agree that directory levels now look correct, but I still seem to get the same issue. Hmm...

**Comment by sseyler** [comment]
Just tried running the updated commands and got the same error at the final step (the developer installation still goes fine, however).

Might there be a problem with my library or include paths that could remedy the issue? Taking a look at the C file that's generated after running `python setup.py build_ext --inplace`, line 590 does indeed have the include statement `#include "src/distributions/distributions.h"`. It would seem like the compiler would be confused by the relative path (unless it's told explicitly where to look) since I'm build from the `randomgen/examples/cython` directory. I don't fully understand all of the caveats and details of sourcing/including of header files, but would it make any sense to change the `extern` statements in the `cimport`ed `*.pxd` files to just point directly to the `*.h` files, and then rely on including the relevant directories somehow?

**Comment by sseyler** [comment]
Okay, I installed just Python 2.7, Numpy (1.14.5), and Cython (0.28.3) in a fresh conda environment. (These were taken from conda-forge, if that matters.) I then re-ran the above sequence of commands and was able to get the examples built without the error. I guess I'll have to a do a bit of digging when I have a chance to figure out what the issue is with my usual environment.

**Comment by bashtage** [comment]
Could be that conda uses its own compilers.

**Comment by sseyler** [comment]
Oddly enough, I'm no longer having problems with my production environment. Other than updating maybe one or two numpy-related packages, I don't know what else changed. I thought it was perhaps a conflict between numpy and numpy-base having different versions, but I can't reproduce the original error even when mixing and matching versions that presumably violate dependencies.

> Could be that conda uses its own compilers.

As in, when using conda to install randomgen? I tried doing everything manually and also with pip after cleaning up old files, so it's still odd that I couldn't manually compile.

Anyway, thanks a lot for the help. I think this issue can be marked solved; I'll post again if I run into the issue again and/or learn anything new.

**Comment by bashtage** [comment]
The simplest solution would be to rename min and max to MIN and MAX.  It would take more source code changes where you could modify the header to check if c++ and only define it not c++.  Could you chec if renaming to MIN and MAX by replacin in distributions.h/distributions.c and min( -> MIN( and max( to MAX(

**Comment by bashtage** [comment]
I should add when I do this locally and use CC=g++ python setup.py build_ext --inplace with the examples it works as expected.

**Comment by sseyler** [comment]
> Could you chec if renaming to MIN and MAX by replacin in distributions.h/distributions.c and min( -> MIN( and max( to MAX(

Yes, I'll do this as soon as I have a chance.

**Comment by bashtage** [comment]
I made this chance in master since it (a) seemed free and (b) seems more consistent with C macro use to use all caps. After I made this change I could run

CC=g++ python setup.py build_ext --inplace 

in the Cython examples folder.

**Comment by sseyler** [comment]
@bashtage Just wanted to confirm that this works for me too.
