### ISSUE TITLE
question

### ISSUE THREAD

**Issue by su314ka** [bashtage/randomgen#229]
Hello,
Sorry. I`m learning and maybe is a nob question.
How can I use randomgen library to generate a random number like script below?
Thank you for your time.

import random
ran = random.randrange(3689,7378)
print (ran)

**Comment by bashtage** [comment]
```
import randomgen as rg
gen = rg.Generator()
gen.integers(3689,7378)
```

or if you are using recent NumPy,
```
import numpy as np
gen = np.random.default_rng()
gen.integers(3689,7378)
```
