### ISSUE TITLE
My notes on testing PRNGs

### ISSUE THREAD

**Issue by peteroupc** [bashtage/randomgen#241]
I see that random generator testing is currently underway in this repository.

On that note, I have written a page on [testing PRNGs for high-quality randomness](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomtest.md).

The following are some points on PRNG testing:

- There are many kinds of PRNGs, including traditional, counter-based, and splittable PRNGs, as well as PRNGs that combine two or more other PRNGs, and there are different approaches to testing all these kinds.

- The testing currently underway uses PractRand on each generator up to 4 TiB (2^42 bytes).  It would be clearer if any results that don't fail at that level say "> 4 TiB" rather than "4 TiB".  Also, I currently consider a PRNG statistically good if it doesn't fail PractRand at 1 TiB (2^40 bytes); is this threshold too low?

- Different PRNGs have different ways to produce independent random number sequences ("streams"), such as by incrementing a seed, or discarding a huge number of outputs.  A given stream strategy can be tested by interleaving the outputs of those streams. The number of streams can be two, three, even ten or more.  Another strategy I have seen used to test [T. Tyl](https://github.com/espadrine)'s "shishua" PRNG is to interleave streams _byte-by-byte_, rather than _output-by-output_.

- A relatively low-quality PRNG can be combined with another number sequence to produce a high-quality PRNG, enough to show no PractRand failure at 1 TiB (see "Combined PRNGs" for details).  A notable example is L'Ecuyer's combined multiple recursive generators.

- Counter-based PRNGs and splittable PRNGs (such as the [PRNG used in JAX](https://github.com/google/jax/blob/master/design_notes/prng.md)) can be based on hash functions and other mixing functions, so it's useful to test these functions to see if they are viable for use in these kinds of PRNGs.  (I give [some of these constructions in detail](https://github.com/peteroupc/peteroupc.github.io/blob/master/hqprng.md).)  On the subject of mixing functions, a [testing procedure by P. Evensen](https://mostlymangling.blogspot.com/2019/01/better-stronger-mixer-and-test-procedure.html) may be of interest.

- Finally, see https://github.com/tweag/random-quality for a similar effort to PRNG testing for Haskell.

**Comment by bashtage** [comment]
Thanks for your thoughts.

> * The testing currently underway uses PractRand on each generator up to 4 TiB (2^42 bytes).  It would be clearer if any results that don't fail at that level say "> 4 TiB" rather than "4 TiB".  Also, I currently consider a PRNG statistically good if it doesn't fail PractRand at 1 TiB (2^40 bytes); is this threshold too low?

In some sense there is no sample large enough to prove anything. It takes about 6 hours for me to test 4TB using about 3 hardware threads. This is the reason why 4TB has been chosen. 95 configurations * 12 hardware thread hours = 1140 cpu core hours. I didn't see much gain in making this a lot larger.

I think the description at the top of the page tried to explain it. I suppose it could use >.

> * Different PRNGs have different ways to produce independent random number sequences ("streams"), such as by incrementing a seed, or discarding a huge number of outputs.  A given stream strategy can be tested by interleaving the outputs of those streams. The number of streams can be two, three, even ten or more.  Another strategy I have seen used to test [T. Tyl](https://github.com/espadrine)'s "shishua" PRNG is to interleave streams _byte-by-byte_, rather than _output-by-output_.

Interleaving bytes isn't very realistic for how the PRNGs in randomgen are used. In most applications, a distinct stream will be used in a single python executable (using say, multiprocessing or on Apache Spark) in which case we care about cross-stream correlation at the output level. The testing here is 8 byte by 8 byte (or for MT19937, 4 byte by 4 byte).  There isn't any reason ex ante to think that byte by byte will produce a more accurate result than n byte by n byte for some n.

From your notes:

> Note that testing nearby sequences produced by leapfrogging is redundant with testing the regular PRNG sequence without streams.

I don't agree with this.  jumping a non-trivial number of steps forward can reveal low-frequency correlations that cannot be detected locally.  If users are using multiple segments from a single seed then this should be protected against.

**Comment by peteroupc** [comment]
>
> > Note that testing nearby sequences produced by leapfrogging is redundant with testing the regular PRNG sequence without streams.
> 
> I don't agree with this. jumping a non-trivial number of steps forward can reveal low-frequency correlations that cannot be detected locally. If users are using multiple segments from a single seed then this should be protected against.

I use leapfrogging to mean assigning N processes a PRNG that each differ from the last by 1 step, then having each such PRNG jump N steps, where N is the number of PRNGs.  It's exactly this which is "redundant with testing the regular PRNG sequence without streams", because the interleaved stream is exactly the same as the regular PRNG's sequence without stream.  Leapfrogging doesn't mean jumping "a nontrivial number of steps forward" (such as 2^64 or 1/goldenratio).

**Comment by bashtage** [comment]
Yes, that is clearly redundant. Does anyone actually do that? The only reason that I could imagine have a leap-frogged sequence would be to take advantage of vector hardware where one uses 4 or 8 copies of the same sequence each separated by 1 draw to output 4 or 8 values in a single iteration. But this is a platform-specific optimization rather than a testing strategy.
