### ISSUE TITLE
RDRAND implementation does not appear to check CF as required in Intel software implementation guide 

### ISSUE THREAD

**Issue by garfi303** [bashtage/randomgen#246]
[Intel's software implementation guide for the RDRAND instruction](https://software.intel.com/content/www/us/en/develop/articles/intel-digital-random-number-generator-drng-software-implementation-guide.html) states that the Carry Flag must be checked after calling RDRAND to assure that the DRNG hasn't been saturated (it can only deliver 800Mbits/sec of randomness)

>## 3.3.1 RDRAND
> 
>RDRAND retrieves a hardware-generated random value from the SP800-90A compliant DRGB and stores it in the destination register given as an argument to the instruction. The size of the random value (16-, 32-, or 64-bits) is determined by the size of the register given. The carry flag (CF) must be checked to determine whether a random value was available at the time of instruction execution.
>
>Note that RDRAND is available to any system or application software running on the platform. That is, there are no hardware ring requirements that restrict access based on process privilege level. As such, RDRAND may be invoked as part of an operating system or hypervisor system library, a shared software library, or directly by an application.
>
>To determine programmatically whether a given Intel platform supports RDRAND, developers can use the CPUID instruction to examine bit 30 of the ECX register. See Reference (7) for details.

In my review of the code, this doesn't seem to be happen.

[randomgen/rdrand.pyx](https://github.com/bashtage/randomgen/blob/master/randomgen/rdrand.pyx)  just calls `rdrand_next64()` and `rdrand_next32()`:
https://github.com/bashtage/randomgen/blob/655bafcc659f15f517bcc931dec2fe02c8a9bcaa/randomgen/rdrand.pyx#L21

And `rdrand_next64` just calls `_rdrand64_step`:
https://github.com/bashtage/randomgen/blob/9e143cf97f58e95103145773564a415119303fae/randomgen/src/rdrand/rdrand.h#L19

**This problem won't show up in unit testing**, because if no other process is calling RDRAND, random bits will be available.
But if you are running on a 12-core CPU, all CPUs share the same RDRAND engine, and that poor engine can only generate 800 MB/sec of random bits:

>## 3.4.1 RDRAND Performance†
>
> In current-generation Intel processors the DRBG runs on a self-timed circuit clocked at 800 MHz and can service a RDRAND transaction (1 Tx) every 8 clocks for a maximum of 100 MTx per second. A transaction can be for a 16-, 32-, or 64-bit RDRAND, and the greatest throughput is achieved with 64-bit RDRANDs, capping the throughput ceiling at 800 MB/sec. These limits are an upper bound on all hardware threads across all cores on the CPU.

In an application that requires a lot of randomness on many cores, this will result in many threads getting ALL ZEROs.

The solution is for this code to test CF and go into a spin-loop. After 10 spins, you can throw an exception (as Intel would have you do), or you can keep spinning (as I would have you do).

**Comment by bashtage** [comment]
I've known about this for a long time but didn't really want to address it since it was a bit difficult in the structure of the NumPy random system.

I have not added ``retries`` which defaults to 10, but can be any non-negative integer (0 for no retries, something large like 1000 (this will delay for up to 40us which should be equivalent to infinite in practice). This was simple and should have been done.

The exception handling was more fragile.  If you just want 64 bits, then it is very robust and will raise RuntimError.  If you want to use it with a NumPy Generator, then it relies on a custom Lock to be used around all calls where the lock checks for an error on exit.  The lock will raise RuntimError if RDRAND fails.

Finally, if you do end up in a failed state, the RDRAND instance should not be used again (and will in fact error).

**Comment by garfi303** [comment]
Our problem is that we need approximately 7 x 10^14 bits of randomness for our application. We are running on a cluster with approximately 160 individual CPUs (1920 cores). It will take 2 hours or so to generate the randomness that we need. We are using numpy. We need to have RDRAND check the carry flag. 

How does one end up in a 'failed state' ?

It would be nice to have a fallback, such as 'use the 0th RDRAND value as a seed for a CSPRNG`

How should we proceed?

**Comment by bashtage** [comment]
You end up in the failed state if RDRAND fails to produce a random value after `retries` retries. 

You can check for RuntimeError and then decide what you would like to do:


Here is an intention fail that uses a trick to make it always fail:

```
import randomgen as rg
import numpy as np

rd = rg.RDRAND()
st = rd.state
st["retries"] = -1  # always fail!
rd.state = st

gen = np.random.Generator(rd)
try:
    gen.integers(0,2**64, dtype=np.uint64, size=10)
except RuntimeError:
    print("RuntimeError hit, do something else or wait a bit and retry")
```

Once it passes CI I will put together a 1.19.2 release with these changes.

**Comment by bashtage** [comment]
I have also added a property `success` of a `RDRAND` instance that you can directly access to see if there has ever been a failure.

**Comment by simsong** [comment]
We're running this in a batch environment. We basically want retries=∞. It looks like with your code we can do:
```
st["retries"] = 1E9
```

Thanks for attending to this.

**Comment by bashtage** [comment]
The wheels are now available on PyPI.
