### ISSUE TITLE
Partially-Sampled Random Numbers

### ISSUE THREAD

**Issue by peteroupc** [bashtage/randomgen#253]
Since you are dealing with random number generation here, I want to let you know about a page I have about so-called [_partially-sampled random numbers_](https://github.com/peteroupc/peteroupc.github.io/blob/master/exporand.md), which could be useful for accurately sampling from certain continuous distributions, including the beta and exponential distributions, to an arbitrary precision and without relying on floating-point arithmetic.  Please comment on this page.

**Comment by bashtage** [comment]
Hi @peteroupc I don't think I have much to add.  We don't have anything like these methods here. Moreover, the generation of variants from distributions is deprecated and will be removed in the next year or so, and only the PRNGs will remain.
