### ISSUE TITLE
Possible off by one error on high/range of random numbers.

### ISSUE THREAD

**Issue by bduvenhage** [bashtage/randomgen#26]
Hi

There seems to be an off by one error in comments at https://github.com/bashtage/randomgen/blob/fa300ad7c4902f1baa8e556915f067fb87de7c93/randomgen/bounded_integers.pyx.in#L159

The comments mention "interval [`low`, `high`)", but also "high : If provided, the largest (signed) **integer to be drawn** from the distribution (see above for behaviour if ``high=None``)."

High seem to be used correctly further on as the largest number to be drawn.

**Comment by bduvenhage** [comment]
Function randint at https://github.com/bashtage/randomgen/blob/fa300ad7c4902f1baa8e556915f067fb87de7c93/randomgen/generator.pyx#L575 uses high as the exclusive upper bound which is the way numpy works, but further down in the calls high is the inclusive upper bound.

**Comment by bashtage** [comment]
Thanks - this is intentional (**I think**) in the internal function and there should be a -1 somewhere to handle the swap from ) to ].  The docstring for the internal function is definitely inconsistent and should be improved.  I'm 99.99% sure that it does the right thing since it passes the NumPy test suite. Just need to get that last .01%, and fix docs.

**Comment by bashtage** [comment]
Here

https://github.com/bashtage/randomgen/blob/fa300ad7c4902f1baa8e556915f067fb87de7c93/randomgen/bounded_integers.pyx.in#L211

or 

https://github.com/bashtage/randomgen/blob/fa300ad7c4902f1baa8e556915f067fb87de7c93/randomgen/bounded_integers.pyx.in#L106

Whew! That would have been annoying.

**Comment by bduvenhage** [comment]
ok, cool. Would it make sense to also rename the open upper bound parameters from 'high' to something like 'high_open' or 'open_upper'. Then have 'high = high_open - 1' for example.
