### ISSUE TITLE
ENH: Allow all values to be set in AesCounter counter range on initialization

### ISSUE THREAD

**Issue by fsssosei** [bashtage/randomgen#267]
`>>> AESCounter(1, counter = (2**128)-4, mode = "sequence")  #is OK`

but
```
>>> AESCounter(1, counter = (2**128)-3, mode = "sequence")
ValueError: counter must be positive and less than 2**128.
>>> AESCounter(1, counter = (2**128)-2, mode = "sequence")
ValueError: counter must be positive and less than 2**128.
>>> AESCounter(1, counter = (2**128)-1, mode = "sequence")
ValueError: counter must be positive and less than 2**128.
```

**Comment by bashtage** [comment]
It is happening because the values are generated in blocks of 4, hence why values within 4 of `2**128` are causing problems.  Can probably be improved. Would require rolling the initial counter, or some other fix.  Not super excited about making this change for what is a very marginal gain.
