### ISSUE TITLE
DOC: COrrect ChaCha's period 

### ISSUE THREAD

**Issue by fsssosei** [bashtage/randomgen#269]
Why is the period of ChaCha 2^{128} -1, not 2^{128} ?
What is the rationale for subtracting one?
Is there any literature?

**Comment by bashtage** [comment]
Probably a typo from copy and paste initial doc string. Same issue probably affects the SPECK128 docstring, as I can't see why it would lose 1 (the usual case for -1 is if 1 value needs to be burned).
