### ISSUE TITLE
Enquiries about EFIIX64

### ISSUE THREAD

**Issue by fsssosei** [bashtage/randomgen#290]
EFIIX64 (also known as efiix64x48)
The name in Pracrand is Efiix64x384
Why is x48 written here and x384 written in Pracrand?

Random_raw (size=None) Is the output period 2^64?

**Comment by bashtage** [comment]
48*8=384. Should probably clarify these are the same.

**Comment by bashtage** [comment]
It is possible something was renamed at some point after this was implemented.

**Comment by fsssosei** [comment]
> 
> 
> 48*8=384. Should probably clarify these are the same.

I see. Thank you

**Comment by zoj613** [comment]
Based on the quote:
_Next is my own efiix (class name is efiix64x384 for the highest quality variant in PractRand 0.93 or efiix64x48 for the highest quality variant in PractRand 0.94 (I decided that the extra quality from larger table sizes wasn't worth the slower seeding and increased memory/cache footprint - it's easily 5-star quality either way))_.

It appears that they are not the same PRNG and that efiix64x48 is a faster version that uses a smaller table size. See: https://sourceforge.net/p/pracrand/discussion/366935/thread/c73ddb7b/#d0fc
