### ISSUE TITLE
In Threefry's docstrings, it says "Philox"?

### ISSUE THREAD

**Issue by fsssosei** [bashtage/randomgen#291]
|  Notes
 |  -----
 |  ThreeFry is a 32 or 64-bit PRNG that uses a counter-based design based on
 |  weaker (and faster) versions of cryptographic functions [1]_. Instances
 |  using different values of the key produce distinct sequences. ``Philox``
 |  has a period of :math:`N*2^{N*W}`

**Comment by bashtage** [comment]
Thanks.
