### ISSUE TITLE
Randomgen declares cython, setuptools, and wheel as runtime requirements

### ISSUE THREAD

**Issue by duncanmmacleod** [bashtage/randomgen#298]
This project declares all of its build requirements as runtime requirements, meaning unnecessary packages get installed. Is it possible to separate the build and runtime lists so that only `numpy` is declared as `install_requires` in `setup.py`?

**Comment by bashtage** [comment]
Would need a new release.  These were just done for simplicity.

**Comment by duncanmmacleod** [comment]
@bashtage, thank you for fixing that so quickly.
