### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ThomasTNO** [bashtage/randomgen#311]
Follow-up of:

> I'll try to get one out later this week.  Would be good to get CI back to working on ARM and FreeBSD.

_Originally posted by @bashtage in https://github.com/bashtage/randomgen/issues/310#issuecomment-1109418689_

Would it be possible to also add wheels for Python3.10 while fixing CI?

**Comment by bashtage** [comment]
Close now.  CI passing in #312

**Comment by bashtage** [comment]
Wheels for 3.10 and 3.11 are available.
