### ISSUE TITLE
Mistakes in xoroshiro128 jump  implementation

### ISSUE THREAD

**Issue by fcharras** [bashtage/randomgen#321]
[here](https://github.com/bashtage/randomgen/blob/3ec0da720990f5dde9e597f9c60d5c25cb1827a5/randomgen/src/xoroshiro128/xoroshiro128.c#L78) and [there](https://github.com/bashtage/randomgen/blob/main/randomgen/xoroshiro128.pyx#L217)

**Comment by fcharras** [comment]
To be more explicit, it seems that those are mistakes because in the first link `xoroshiro128_next(&state->s[0]);` should be `xoroshiro128plusplus_next(&state->s[0]);` and for the second links the condition should be the other way around (effectively impacting jump functions of both xoroshiro128+ and xoroshiro128++)

**Comment by bashtage** [comment]
@fcharras Sorry for missing this issue for so long.  Fixed now and will be out in next release.
