### ISSUE TITLE
invalid bytes?

### ISSUE THREAD

**Issue by mrx23dot** [bashtage/randomgen#346]
```
from numpy.random import Generator
from randomgen import AESCounter

 r546=AESCounter(seed=0, counter=0, mode="sequence").random_raw(size=None, output=True)
 r546= r546.to_bytes(16, byteorder='little').hex()
```
gives '**3883cf555803f8ab**0000000000000000'

but different form, starting from beginning
```
rg2 = Generator(AESCounter(seed=0, counter=0, mode="sequence"))
curr= rg2.bytes(8).hex()
```
gives '**5ab7e3eeba6fcda0**'

I don't see much similarity, why is it that different, why don't they match? Which one is valid?
Are there test vectors?

randomgen==1.23.1
numpy==1.19.5
Python 3.7.0 64bit

**Comment by bashtage** [comment]
The native size of AES is 128bits, so you only get the entire value when you generate 2 raw values. Essentially you were seeing different halves of the same 128 bit value. `random_raw` is mostly for direct testing, and you get the upper first, then he lower, while when you use `bytes` you get that value of `next_uint64` which is the lower first, then the upper.

```python
from numpy.random import Generator
from randomgen import AESCounter

r546=AESCounter(seed=0, counter=0, mode="sequence").random_raw(size=2, output=True)
b =  [bytearray(v.tobytes()) for v in r546]
b[0].extend(b[1])
h1 = bytes(b[0]).hex()
print(h1)
```
```
3883cf555803f8abfbd5c4b4668bb194
```


```python
rg2 = Generator(AESCounter(seed=0, counter=0, mode="sequence"))
h2 = rg2.bytes(16).hex()
print(h2)
```

```
3883cf555803f8abfbd5c4b4668bb194
```

```python
h1 == h2
```
```
True
```

It is easier to use `integers`


```python
AESCounter(seed=0, counter=0, mode="sequence").random_raw(size=2, output=True)
```
```
array([12391658052641588024, 10714498261726844411], dtype=uint64)
```

```python
g = Generator(AESCounter(seed=0, counter=0, mode="sequence"))
g. integers(np.iinfo(np.uint64).max, size=2, dtype="u8", endpoint=True)
```
```
array([12391658052641588024, 10714498261726844411], dtype=uint64)
```

**Comment by bashtage** [comment]
I think this is just a matter of interpretation.  From the point of view of randomgen, it is a 64bit PRNG even if the atomic unit of generation if 128-bits (in fact, even crank of the algo used produces 6*128 pseudo random bits). Being a 64-bit PRNG from the POV fo randomgen means that you get at least 64bits from each value produced. This is in contrast of something like the standard MT which has to use 2 32-bit values to produce a 64-bit pseudo random value.

HC128, for example, produces a lot of bits in every interaction.  These are then dealt out in 64-bit chunks.
