### ISSUE TITLE
Numpy 2.0 compatibility

### ISSUE THREAD

**Issue by Shoeboxam** [bashtage/randomgen#360]
I am getting the following error when using randomgen on Numpy 2.0 (which has just released today):

```
  File "randomgen/aes.pyx", line 1, in init randomgen.aes
  File "randomgen/common.pyx", line 1, in init randomgen.common
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

No issue on Numpy 1.26.4, the max prior version. I think it's likely that Numpy's ABI has changed in 2.0, causing an incompatibility.

Thanks for maintaining this package!

**Comment by bashtage** [comment]
I will try and get to it next week.  Needs a decent refactor n

**Comment by radohristov** [comment]
Hi Kevin,

sorry to bother you, is there any update on this issue?

Thnks & nice day, Radoslav

**Comment by bashtage** [comment]
Very close now.  Main works on NumPy 2 (1.22.3+). Hope to have release in the next few days.

**Comment by bashtage** [comment]
randomgen 2.0.0 has been released with NumPy compatibility.
