### ISSUE TITLE
permutation seems MUCH slower than shuffle?

### ISSUE THREAD

**Issue by nbecker** [bashtage/randomgen#42]
IIUC, permutation(x) is the same as shuffle(x.copy()).  But the timing is very different!

In a test using line_profiler, I'm getting:
    44       539        946.0      1.8      1.7      shuffled = points.copy()
    45       539       2451.0      4.5      4.4      rs.shuffle(shuffled)
    46       539      44780.0     83.1     80.7      shuffled = rs.permutation(shuffled)

**Comment by bashtage** [comment]
I'm not sure what is going on here.  On my machine I see:

```
import randomgen as rg

rs = rg.generator.RandomGenerator(rg.mt19937.MT19937())

x = rs.randn(100000)

%timeit rs.shuffle(x)
3.69 ms ± 248 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit rs.permutation(x)
4.1 ms ± 276 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

What is `points`?  There are fast paths in permutation that are like shuffle + copy. But there is a slow path as well if the input is not 1d.

Slow path:
```
        # Shuffle index array, dtype to ensure fast path
        idx = np.arange(arr.shape[0], dtype=np.intp)
        self.shuffle(idx)
        return arr[idx]
```

**Comment by nbecker** [comment]
It is 1d. Very strange. I looked at permutation source code and it seems to just wrap shuffle.

**Comment by bashtage** [comment]
It does.  Can you reproduce it now?  If so, could you post complete example including the PRNG used?

**Comment by nbecker** [comment]
It's likely that python line_profiler is lying.  If I simply run time on CLI I don't see the differences that line_profiler is seeing.

**Comment by bashtage** [comment]
Thanks for updating.
