### ISSUE TITLE
unable to import "randomgen" on colab

### ISSUE THREAD

**Issue by HassanAliKhatim** [bashtage/randomgen#43]
I have been successfully using "randomgen" for a past couple of weeks. However, recently, I encountered this error and now, I am unable to import "randomgen" on colab. The commands are as follows:

!pip install randomgen
import randomgen

![image](https://user-images.githubusercontent.com/46008837/52777551-e565e080-3065-11e9-9c68-0089ca2ff7a8.png)

When I try to import it the second time, it displays the following error:

![image](https://user-images.githubusercontent.com/46008837/52777608-04fd0900-3066-11e9-85ef-150d7df03685.png)

Any ideas please?

**Comment by bashtage** [comment]
This is news to me.  I might cross-post to NumPy.  I wonder if it is an issue with the latest Cython?  Can you try downgrading Cython to something like 0.29.2?

________________________________

**Comment by HassanAliKhatim** [comment]
Thank you for your feedback.

It issues the same error. However, if I replace "!pip install randomgen" with "!pip install git+https://github.com/bashtage/randomgen.git" it successfully imports the library and the issue is solved :-) .

**Comment by bashtage** [comment]
Thanks - must be a binary incompatibility between the wheels the NumPy version installed (or maybe something with the Cython and NumPy combination).

**Comment by bashtage** [comment]
I suppose if you could update to NumPy 1.16 then it might go away.

**Comment by HassanAliKhatim** [comment]
Yes, it works. Thanks.

**Comment by bashtage** [comment]
Thanks. Going to close.
