### ISSUE TITLE
1.16.2 broke Python 2.7 support

### ISSUE THREAD

**Issue by jonasrauber** [bashtage/randomgen#68]
This commit breaks Python 2.7 support:

https://github.com/bashtage/randomgen/commit/27bd211682775964e6ef87f7d3191a24fe8a88dc

Now I am all in favor of moving to Python 3 only, but the README says 1.16 will still support Python 2.7 so this should probably be fixed. I only noticed because we have a library that has `randomgen` as a requirement and its tests for Python 2.7 started failing.

**Comment by bashtage** [comment]
I should have labeled the recent release as 1.17. This is what is going into NumPy which is 3+ only now (in master), and so I needed to coordinate. 

I'll see how hard it is to get back to 2.7.

**Comment by jonasrauber** [comment]
I've specified "randomgen<=1.16.1" as a requirement for python 2 now. This should solve it for me. Don't make to much of an effort for Python 2.7.

**Comment by bashtage** [comment]
This is fixed now in 1.16.3.
